project_id = "defense-tracker-v9-ci"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.seed]
enabled = false

[functions.invite-member]
verify_jwt = false

[functions.access-applications]
verify_jwt = false
