version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: "/deploy"
    schedule:
      interval: weekly
      day: monday
      time: "03:15"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: "/web/v9-auth"
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:45"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
